module.exports = {
  apps: [
    {
      name: "quickair-strapi",
      cwd: "/var/www/quickair/apps/strapi",
      script: "npm",
      args: "run start",
      interpreter: "none",
      env: {
        NODE_ENV: "production",
        PATH: "/root/.nvm/versions/node/v22.21.1/bin:" + process.env.PATH,
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      error_file: "/var/www/quickair/logs/strapi-error.log",
      out_file: "/var/www/quickair/logs/strapi-out.log",
      time: true,
    },
    {
      name: "quickair-frontend",
      cwd: "/var/www/quickair/apps/frontend",
      script: "npm",
      args: "run start",
      interpreter: "none",
      env: {
        NODE_ENV: "production",
        PORT: 3000,
        NEXT_PUBLIC_STRAPI_URL: "https://quickair-admin.build8.dev",
        NEXT_PUBLIC_SITE_URL: "https://quickair.build8.dev",
        PATH: "/root/.nvm/versions/node/v22.21.1/bin:" + process.env.PATH,
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      error_file: "/var/www/quickair/logs/frontend-error.log",
      out_file: "/var/www/quickair/logs/frontend-out.log",
      time: true,
    },
  ],
};
